[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[project]
name = "ai-research-assistant"
version = "0.1.0"
description = "AI Research Assistant"
readme = "README.md"
requires-python = ">=3.12,<3.13"

dependencies = [
    "python-dotenv>=1.0.1",
    "streamlit>=1.38.0",
    "langgraph>=0.2.74",
    "langchain>=0.3.27",
    "langchain-core>=0.3.27",
    "langchain-groq>=0.3.0",
    "langchain-tavily>=0.1.5",
    "pydantic>=2.8.2",
]
